sonar.projectKey=TEGRASW_Metropolis-perf_SDG_pcb-aoi
sonar.projectName=pcb-aoi
sonar.qualitygate.wait=true

sonar.python.version=3.10
sonar.sources=scripts
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**,\
  **/.venv/**,\
  **/build/**,\
  **/dist/**,\
  **/output/**,\
  **/assets/**,\
  **/__pycache__/**,\
  **/*.egg-info/**
